version: "3"

services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
      #image: internetsystemsconsortium/bind9:9.16
    environment:
      - BIND9_USER=root
      - TZ=Asia/Jakarta
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    external: true
